name: slides

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository and submodules
      - uses: actions/checkout@v2
        with:
          submodules: recursive
        uses: textbook/git-checkout-submodule-action@master
      - name: Install dependencies
        run: brew install gdal geos udunits gifski imagemagick
      - uses: r-lib/actions/setup-r@master
      - name: Install R packages
        run: Rscript courses_tools/R/install.R
      - name: Generate slides
        run: Rscript courses_tools/R/render.R
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./render
