name: slides

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install gdal geos udunits gifski 
      - uses: r-lib/actions/setup-r@master
      - name: Install R packages
        run: Rscript courses_tools/R/install.R
      - name: Generate slides
        run: Rscript courses_tools/R/render.R
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./render
